### ISSUE TITLE
Correction 

### ISSUE THREAD

**Issue by werdl** [Aahan-in-Space/aahaninspace-website#24]
PHP - PHP Hypertext Processor

It's a recursive acronym

**Comment by 2010person** [comment]
Oh yeah I didn't notice

**Comment by 2010person** [comment]
It's meant to be Personal HyperText Processor that was an error. Thanks

**Comment by 2010person** [comment]
Where does it say that?

**Comment by werdl** [comment]
Heading in the readme

**Comment by 2010person** [comment]
I am going to change it anyways soon, because 000webhost went wrong so it will just be frontend for a while. Thanks!
